version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - internal-network
    restart: unless-stopped

  golang:
    container_name: golang_container
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge

volumes:
  postgres: